### PR TITLE
Updated UI along with Pause button

### PR DESCRIPTION
**Pull request by SuriyaaVijay**
Fix for Issue #11

image
image

Hi Rishi,
I have added the pause and play buttons along with a good UI fix.
Designed a new landing page perfectly too.

Regards,
Suriyaa

### CODE REVIEW

**Comment by rishibaghel25** [comment]
It's looking amazing 🤩 I'll merge it after review. Can you tell me your email or any other contact ? ..

**Review by ShambhaviVijay — APPROVED** [review]
The UI looks good, we can merge it!

**Comment by SuriyaaVijay** [comment]
> It's looking amazing 🤩 I'll merge it after review. Can you tell me your email or any other contact ? ..

thank you rishi !

yes, you can contact me at 
Gmail: suriyaa.cse50@gmail.com
Linkedin: https://www.linkedin.com/in/suriyaa-v/

**Comment by SuriyaaVijay** [comment]
Any update @rishibaghel25 bro

**Pull request merged**
